language: node_js

os: linux

node_js:
  - node

addons:
  chrome: stable

before_script:
  - npm install -g chromedriver

script:
  - yarn tslint
  - yarn build
  - yarn phantomjs-test
  - yarn browser-test
